#!/usr/bin/env bash
# I1 dev harness: run the ClaudeWatch watch app in the Connect IQ simulator
# against a LOCAL daemon serving your real ~/.claude sessions.
#
# This is the local-simulator path (plain http://localhost, which the simulator
# allows). The real Forerunner 165 needs HTTPS via your Cloudflare tunnel - see
# docs/integration.md.
#
# Usage:  tools/dev/run-sim.sh        (Ctrl-C to tear everything down)
# Env:    PORT (default 8787), CLAUDEWATCH_TOKEN (default devtoken),
#         CIQ_DEVICE (default fr165)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

PORT="${PORT:-8787}"
DEV_TOKEN="${CLAUDEWATCH_TOKEN:-devtoken}"
DEVICE="${CIQ_DEVICE:-fr165}"
CONFIG="apps/watch/source/Config.mc"

# Discover the newest installed Connect IQ SDK bin.
SDK_BIN="$(ls -d "$HOME/Library/Application Support/Garmin/ConnectIQ/Sdks/"*/bin 2>/dev/null | sort | tail -1 || true)"
if [[ -z "$SDK_BIN" || ! -x "$SDK_BIN/monkeydo" ]]; then
  echo "error: Connect IQ SDK not found. Install it and retry." >&2; exit 1
fi
export PATH="$SDK_BIN:$PATH"

DAEMON_PID=""
CONFIG_BACKUP=""
STARTED_DAEMON=0

cleanup() {
  # Restore the user's real Config.mc if we swapped it.
  if [[ -n "$CONFIG_BACKUP" && -f "$CONFIG_BACKUP" ]]; then
    mv -f "$CONFIG_BACKUP" "$CONFIG"
    echo "restored your Config.mc"
  fi
  # Only stop the daemon if this script started it. Free the port (this also
  # kills the node child that npm spawns), then reap the npm wrapper.
  if [[ "$STARTED_DAEMON" == "1" ]]; then
    lsof -tiTCP:"$PORT" -sTCP:LISTEN 2>/dev/null | xargs -r kill 2>/dev/null || true
    [[ -n "$DAEMON_PID" ]] && kill "$DAEMON_PID" 2>/dev/null || true
    echo "stopped local daemon"
  fi
}
trap cleanup EXIT INT TERM

# 1. Ensure a daemon is serving on $PORT (start one if not).
if curl -s -o /dev/null "http://localhost:$PORT/sessions" 2>/dev/null; then
  echo "using daemon already listening on :$PORT"
else
  echo "starting local daemon on :$PORT (token: $DEV_TOKEN) ..."
  # No `setsid` on macOS; a plain background job is fine (cleanup frees the port).
  CLAUDEWATCH_TOKEN="$DEV_TOKEN" PORT="$PORT" npm run serve >/tmp/claudewatch-daemon.log 2>&1 &
  DAEMON_PID=$!
  STARTED_DAEMON=1
  # Wait until it answers (any HTTP status = listening), up to ~15s; fail loudly on timeout.
  ready=0
  for _ in $(seq 1 30); do
    code="$(curl -s -o /dev/null -w '%{http_code}' "http://localhost:$PORT/sessions" 2>/dev/null || echo 000)"
    if [[ "$code" != "000" ]]; then ready=1; break; fi
    kill -0 "$DAEMON_PID" 2>/dev/null || { echo "daemon died on startup; see /tmp/claudewatch-daemon.log" >&2; exit 1; }
    sleep 0.5
  done
  [[ "$ready" == "1" ]] || { echo "daemon did not start listening on :$PORT within 15s; see /tmp/claudewatch-daemon.log" >&2; exit 1; }
fi

# 2. Point Config.mc at the local daemon (backing up any real one).
if [[ -f "$CONFIG" ]]; then CONFIG_BACKUP="$(mktemp)"; cp "$CONFIG" "$CONFIG_BACKUP"; fi
cat > "$CONFIG" <<EOF
// AUTO-GENERATED by tools/dev/run-sim.sh for local simulator testing.
// Your real Config.mc is backed up and restored on exit.
using Toybox.Lang;

module Config {
    const BASE_URL as Lang.String = "http://localhost:$PORT";
    const TOKEN as Lang.String = "$DEV_TOKEN";
    const LIMIT as Lang.Number = 10;
}
EOF

# 3. Build the watch app.
echo "building apps/watch for $DEVICE ..."
bash tools/build-watch.sh

# 4. Launch the simulator (detached) if not already open, then load the app.
if ! pgrep -f "ConnectIQ.app/Contents/MacOS/simulator" >/dev/null 2>&1; then
  open "$SDK_BIN/ConnectIQ.app"
  sleep 8
fi
echo "loading app onto $DEVICE simulator ..."
monkeydo "apps/watch/bin/ClaudeWatch.prg" "$DEVICE" &

echo ""
echo "ClaudeWatch is running in the simulator against http://localhost:$PORT"
echo "Press Ctrl-C here to tear everything down."
# Block so the daemon stays up while you use the simulator.
wait
